### ISSUE TITLE
Cryptic Bearer Token

### ISSUE THREAD

**Issue by Staubgeborener** [witnessmenow/arduino-twitter-api#1]
Hey, i want to try your example. I created my App in Twitter, so i get my consumer key / secret. But my bearer token seems to be a little bit crypted. May you know whats wrong here?

![unbenannt](https://user-images.githubusercontent.com/28908603/32414444-15372138-c227-11e7-8648-568ea8a73285.png)

**Comment by Staubgeborener** [comment]
Well, nevermind. This is the correct way to get the bearer token:
``curl -u "$CONSUMER_KEY:$CONSUMER_SECRET" \
    --compressed \
    --data 'grant_type=client_credentials' \
    'https://api.twitter.com/oauth2/token'``

**Comment by witnessmenow** [comment]
What needed up being the problem?

Glad you got sorted!
